sudo: required
language: rust
cache: cargo
env: RUST_BACKTRACE=1
branches:
  only:
    - master
    - dev

matrix:
  include:
    - os: linux
      rust: 1.34.0
      script:
        - sh scripts/build-external-crate.sh
        - sh scripts/test-no-features.sh
        - sh scripts/test-runnable-feature.sh
    - os: linux
      rust: stable
      script:
        - sh scripts/build-external-crate.sh
        - sh scripts/test-no-features.sh
        - sh scripts/test-runnable-feature.sh
    - os: linux
      rust: nightly
      addons:
        apt:
          packages:
            - libssl-dev
      before_cache:
        - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
      script:
        - sh scripts/build-external-crate.sh
        - sh scripts/test-no-features.sh
        - sh scripts/test-format-feature.sh
        - sh scripts/test-runnable-feature.sh
        - sh scripts/test-racer-completion-feature.sh
        - sh scripts/test-default-features.sh
      after_success:
        - cd papyrus
        - cargo tarpaulin -v --out Xml
        - bash <(curl -s https://codecov.io/bash)
    - os: windows
      rust: stable
      script:
        - sh scripts/build-external-crate.sh
        - sh scripts/test-no-features.sh
        - sh scripts/test-runnable-feature.sh
    - os: linux
      rust: stable
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
        - cargo install-update -a
      script:
        - cd papyrus && cargo build --no-default-features --features=runnable && cd ..
        - mdbook build docs
        - mdbook test docs -L papyrus/target/debug,papyrus/target/debug/deps
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: docs/book
        keep-history: false
        on:
          branch: master
  allow_failures:
    - os: windows


