sudo: required
language: rust
cache: cargo
env:
  - RUSTFLAGS='--cfg procmacro2_semver_exempt'
os:
  - windows
  - linux
  - osx
rust:
  - nightly
jobs:
  include:
  - stage: deploy
    script:
    - bash pass_build_push.sh