sudo: required
language: rust
cache: cargo

matrix:
  include:
    - os: "linux"
      rust:
        - stable
        - beta
        - nightly
      addons:
        apt:
          packages:
            - libssl-dev
    - os: "windows"
      rust:
        - stable

before_cache: |
  if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

script:
  - cd ..
  - git clone https://github.com/kurtlawrence/azul.git
  - cd papyrus/
  - cargo clean
  - cargo build
  - cargo test -- --test-threads=1

after_success: |
  if [[  "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --skip-clean -v --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
