sudo: required
language: rust
cache: cargo
env: RUST_BACKTRACE=1

matrix:
  include:
    - os: linux
      rust: 1.30.0
      script:
        - sh scripts/build-external-crate.sh
        - sh scripts/test-no-features.sh
        - sh scripts/test-runnable-feature.sh
    - os: linux
      rust: stable
      script:
        - sh scripts/build-external-crate.sh
        - sh scripts/test-no-features.sh
        - sh scripts/test-runnable-feature.sh
    - os: linux
      rust: beta
      script:
        - sh scripts/build-external-crate.sh
        - sh scripts/test-no-features.sh
        - sh scripts/test-runnable-feature.sh
    - os: linux
      rust: nightly
      addons:
        apt:
          packages:
            - libssl-dev
      before_cache: |
        if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == nightly ]]; then
          RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
        fi
      script:
        - sh scripts/build-external-crate.sh
        - sh scripts/test-no-features.sh
        - sh scripts/test-format-feature.sh
        - sh scripts/test-runnable-feature.sh
        - sh scripts/test-racer-completion-feature.sh
        - sh scripts/test-default-features.sh
      after_success: |
        if [[  "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == nightly ]]; then
          cargo tarpaulin -v --out Xml
          bash <(curl -s https://codecov.io/bash)
        fi
    - os: windows
      rust: stable
      script:
        - sh scripts/build-external-crate.sh
        - sh scripts/test-no-features.sh
        - sh scripts/test-runnable-feature.sh
    - os: windows
      rust: stable
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
        - cargo install-update -a
      script:
        - mdbook build docs/book && mdbook test docs/book
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: docs/book/book
        keep-history: false
        on:
          branch: master
  allow_failures:
    - os: windows


