sudo: required
language: rust
cache: cargo
script:
  - cd ..
  - git clone https://github.com/kurtlawrence/azul.git
  - cd papyrus/
  - cargo clean
  - cargo build
  - cargo test -- --test-threads=1
os:
  - linux
  - windows
  - osx
rust:
  - stable
  - beta

matrix:
  include:
    - os: "linux"
      addons:
        apt:
          packages:
            - libssl-dev
  allow_failures:
    - os: "windows"

before_cache: |
  if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

after_success: |
  if [[  "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --skip-clean -v --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi