[package]
name = "papyrus"
version = "0.1.2"
authors = ["kurt <kurtlawrence92@gmail.com>"]
description = "A rust script runner"
license = "MIT"
website = "https://github.com/kurtlawrence/papyrus"

[badges]
travis-ci = { repository = "kurtlawrence/papyrus" }


[dependencies]
argparse = "0.2"
failure = "0.1"