[package]
name = "papyrus"
version = "0.6.1"
authors = ["kurt <kurtlawrence92@gmail.com>"]
description = "A rust repl and script runner"
license = "MIT"
homepage = "https://github.com/kurtlawrence/papyrus"
repository = "https://github.com/kurtlawrence/papyrus"
documentation = "https://docs.rs/papyrus/"
readme = "README.md"
keywords = [ "repl", "script" ]

[badges]
travis-ci = { repository = "kurtlawrence/papyrus" }

[dependencies]
argparse = "0.2"
failure = "0.1"
dirs = "1.0"
linefeed = "0.5"
log = "0.4"
syn = {	version = "0.15", default-features = false,	features =  [ "full" ] }
simplelog = "0.5"
colored = "1.6"
term_cursor = "0.2"
reqwest = "0.9"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benches"
harness = false