[package]
name = "papyrus"
version = "0.8.0"
authors = ["kurt <kurtlawrence92@gmail.com>"]
description = "A rust repl and script runner"
license = "MIT"
homepage = "https://github.com/kurtlawrence/papyrus"
repository = "https://github.com/kurtlawrence/papyrus"
documentation = "https://docs.rs/papyrus/"
readme = "README.md"
keywords = [ "repl", "script" ]
edition = "2018"

[badges]
travis-ci = { repository = "kurtlawrence/papyrus" }

[dependencies]
# My crates
#linefeed = { git = "https://github.com/kurtlawrence/linefeed" }
linefeed = { path = "/linefeed" }
cratesiover = "2.2"
cmdtree = "0.7"
shh = "1.0"

# crates.io
dirs = "1.0"
log = "0.4"
syn = {	version = "0.15", default-features = false,	features =  [ "full" ] }
colored = "1.8"
term_cursor = "0.2"
reqwest = "0.9"
libloading = "0.5"
crossbeam = "0.7"
sublime_fuzzy = "0.6"
racer = "2.1"
fxhash = "0.2"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benches"
harness = false