[package]
name = "papyrus"
version = "0.8.0"
authors = ["kurt <kurtlawrence92@gmail.com>"]
description = "A rust repl and script runner"
license = "MIT"
homepage = "https://github.com/kurtlawrence/papyrus"
repository = "https://github.com/kurtlawrence/papyrus"
documentation = "https://docs.rs/papyrus/"
readme = "README.md"
keywords = [ "repl", "script" ]
edition = "2018"

[badges]
travis-ci = { repository = "kurtlawrence/papyrus" }

[dependencies]
# My crates
cansi = 			{ path = "/cansi",		default-features = false,	optional = true }
cratesiover =		{ version = "2.2",		default-features = false,	optional = true }
cmdtree = 			{ version = "0.8",		default-features = false }
shh = "1.0"

# crates.io
crossbeam-channel =	{ version = "0.3",		default-features = false }
crossbeam-utils =	{ version = "0.6",		default-features = false }
dirs = "1.0"
log = "0.4"
mortal =			{ version = "0.2",		default-features = false,	optional = true }
syn = {	version = "0.15", default-features = false,	features =  [ "full" ] }
colored = "1.8"
libloading = "0.5"
linefeed = 			{ path = "/linefeed",	default-features = false,	optional = true }
racer = 			{ version = "2.1",		default-features = false,	optional = true,	features = [ "metadata" ] }
term_cursor =		{ version = "0.2",		default-features = false,	optional = true }
fxhash = "0.2"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "benches"
harness = false

[features]
default = [ "runnable", "racer-completion" ]
# allows to just run the repl
runnable = [ "cansi", "cratesiover", "linefeed", "mortal", "term_cursor" ]
# requires nightly
racer-completion = [ "racer" ]

[[bin]]
name = "papyrus"
path = "src/main.rs"
required-features = [ "runnable" ]