name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: '00 07 * * 0'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
        
      - name: Cache .cargo
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-coverage-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-coverage-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
     
      - name: Build external crate test dependency
        run: |
          cd test-resources/external_crate
          cargo build
          cd ../..
        
      - name: Build external kserd test dependency
        run: |
          cd test-resources/external_kserd
          cargo build
          cd ../..
            
      - name: Install tarpaulin
        run: |
          sudo apt-get install libssl-dev
          cargo install cargo-tarpaulin
          
      - name: Generate and Upload Coverage
        run: |
          cargo tarpaulin -v --out Xml
          bash <(curl -s https://codecov.io/bash)
