name: Rust

on: [push, pull_request]

jobs:
  all-features:
    name: All features on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt
#     - name: Build external crate
#       run: |
#         cd test-resources/external_crate
#         cargo build
#         cd ../..
#     - name: Run tests
#       run: cargo test
    - name: Run tests
      shell: bash
      run: ./scripts/test-default-features.sh
